# Automation Engine Default Config File

name = "automation-engine"
metrics_port = 9832

[mqtt]
host = "::1"
port = 1883
enable_tls = false
force_protocol_version_3_1 = true

[plugins.hue]
topic_prefix = "hue2mqtt"